"""empty message

Revision ID: d4be37dff357
Revises: ec4947284bd4
Create Date: 2023-08-21 16:54:18.993554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4be37dff357'
down_revision = 'ec4947284bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokedex',
    sa.Column('poke_name', sa.String(), nullable=False),
    sa.Column('poke_img', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('poke_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokedex')
    # ### end Alembic commands ###
